name: "website-dev"

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules # Named module will store dependencies on startup
    ports:
      - "3000:3000"

volumes:
  node_modules: